"""
Test that scene randomization works correctly.

This script:
1. Loads a scene
2. Loads baseline test data (generated by generate_test_data_randomization.py)
3. Applies randomization
4. Verifies that objects that should be randomized were randomized
5. Verifies that objects that should not be randomized (e.g., robot) were not randomized

Checks:
- Dynamics values (mass, inertia, friction)
- Texture/material values (via camera images and material properties)
- Lighting values
"""

import json
import os
from pathlib import Path

import cv2
import mujoco
import numpy as np
import pytest
from mujoco import MjData, MjModel
from skimage.metrics import structural_similarity as ssim

from mlspaces_tests.data_generation.config import RandomizationTestConfig
from mlspaces_tests.data_generation.generate_test_data_randomization import add_test_camera
from molmo_spaces.env.arena.arena_utils import get_all_bodies_with_joints_as_mlspaces_objects
from molmo_spaces.env.arena.randomization.dynamics import DynamicsRandomizer
from molmo_spaces.env.arena.randomization.lighting import LightingRandomizer
from molmo_spaces.env.arena.randomization.texture import TextureRandomizer, setup_empty_materials
from molmo_spaces.molmo_spaces_constants import get_resource_manager, get_scenes
from molmo_spaces.utils.lazy_loading_utils import install_scene_with_objects_and_grasps_from_path
from molmo_spaces.utils.scene_metadata_utils import get_scene_metadata

RANDOMIZED_TEST_DATA_DIR = get_resource_manager().symlink_dir / "test_data" / "test_randomized_data"
OUTPUT_DATA_DIR = Path(__file__).resolve().parent / "test_output" / "randomization"


def load_baseline_data(metadata_file: Path) -> dict:
    """Load baseline test data from metadata JSON file and associated NPY files."""
    with open(metadata_file, "r") as f:
        metadata = json.load(f)

    # Resolve file paths relative to metadata file directory
    metadata_dir = metadata_file.parent

    # Resolve NPY file paths (they should be relative to metadata directory)
    dynamics_file = metadata_dir / metadata["files"]["dynamics"]
    texture_file = metadata_dir / metadata["files"]["texture_material"]
    lighting_file = metadata_dir / metadata["files"]["lighting"]

    # Resolve camera image paths
    camera_images = metadata["camera_images"].copy()
    for cam_name, cam_data in camera_images.items():
        if "image_path" in cam_data and cam_data["image_path"]:
            # Resolve relative to metadata directory
            image_path = metadata_dir / cam_data["image_path"]
            camera_images[cam_name]["image_path"] = str(image_path)

    # Load NPY files
    baseline_data = {
        "dynamics": np.load(dynamics_file, allow_pickle=True).item(),
        "texture_material": np.load(texture_file, allow_pickle=True).item(),
        "lighting": np.load(lighting_file, allow_pickle=True).item(),
        "camera_images": camera_images,
        "scene_path": metadata["scene_path"],
        "model_info": metadata["model_info"],
    }

    return baseline_data


def check_dynamics_randomization(
    model: MjModel,
    data: MjData,
    baseline: dict,
    dynamics_randomizer: DynamicsRandomizer,
    tolerance: float = 1e-6,
) -> dict:
    """Check that dynamics randomization worked correctly."""
    results = {
        "randomized": {},
        "errors": [],
    }

    # Get all objects with joints
    objects = get_all_bodies_with_joints_as_mlspaces_objects(model, data)

    for obj in objects:
        obj_name = obj.name
        object_id = obj.object_id

        if obj_name not in baseline:
            continue  # Object not in baseline (might be new or filtered)

        baseline_obj = baseline[obj_name]

        # Get current values
        total_mass = float(model.body_subtreemass[object_id])
        inertia = np.array(model.body_inertia[object_id])
        baseline_inertia = np.array(baseline_obj["inertia"])

        # Check mass
        mass_diff = abs(total_mass - baseline_obj["mass"])
        inertia_diff = np.linalg.norm(inertia - baseline_inertia)

        # Check friction
        object_root_id = model.body(object_id).rootid[0]
        friction_changed = False
        for geom_id, baseline_friction in baseline_obj["geom_frictions"].items():
            geom_id_int = int(geom_id)
            geom_body_id = model.geom(geom_id_int).bodyid.item()
            geom_root_id = model.body(geom_body_id).rootid[0]
            if geom_root_id == object_root_id:
                current_friction = np.array(model.geom_friction[geom_id_int])
                baseline_friction_arr = np.array(baseline_friction)
                if np.linalg.norm(current_friction - baseline_friction_arr) > tolerance:
                    friction_changed = True
                    break

        # All objects SHOULD be randomized
        if mass_diff > tolerance or inertia_diff > tolerance or friction_changed:
            results["randomized"][obj_name] = {
                "mass_diff": mass_diff,
                "inertia_diff": inertia_diff,
                "friction_changed": friction_changed,
                "status": "OK - randomized",
            }
        else:
            results["randomized"][obj_name] = {
                "mass_diff": mass_diff,
                "inertia_diff": inertia_diff,
                "friction_changed": friction_changed,
                "error": "Object was not randomized but should be",
            }
            results["errors"].append(
                f"ERROR: Object '{obj_name}' was not randomized "
                f"(mass_diff={mass_diff:.6f}, inertia_diff={inertia_diff:.6f}, "
                f"friction_changed={friction_changed})"
            )

    return results


def check_texture_material_randomization(
    model: MjModel, baseline: dict, tolerance: float = 1e-6
) -> dict:
    """Check that texture/material randomization worked correctly.

    Note: Only compares material names and RGBA values, not texture bitmaps
    (bitmaps are not saved in baseline to reduce file size).
    """
    results = {
        "randomized": {},
        "errors": [],
    }

    baseline_geom_materials = baseline.get("geom_materials", {})
    baseline_geom_rgba = baseline.get("geom_rgba", {})

    # Note: Not all geoms are randomized (only by category), so we just track
    # which ones were captured in baseline and can optionally check if they changed
    # We do NOT compare texture bitmaps (they are not saved in baseline)
    for geom_id_str, mat_name in baseline_geom_materials.items():
        geom_id = int(geom_id_str)
        geom_name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, geom_id)
        geom = model.geom(geom_id)
        current_mat_id = geom.matid.item()
        # Check if material changed
        material_changed = False
        if current_mat_id >= 0:
            current_mat_name = mujoco.mj_id2name(
                model, mujoco.mjtObj.mjOBJ_MATERIAL, current_mat_id
            )
            if current_mat_name != mat_name:
                material_changed = True

        # Check RGBA
        rgba_changed = False
        if geom_id_str in baseline_geom_rgba:
            baseline_rgba = np.array(baseline_geom_rgba[geom_id_str])
            current_rgba = np.array(geom.rgba)
            rgba_diff = np.linalg.norm(current_rgba - baseline_rgba)
            if rgba_diff > tolerance:
                rgba_changed = True

        # Track changes (note: not all geoms are randomized by category)
        # Note: We do NOT check texture bitmaps - they are not saved in baseline
        if material_changed or rgba_changed:
            results["randomized"][geom_id] = {
                "name": geom_name if geom_name else f"geom_{geom_id}",
                "material_changed": material_changed,
                "rgba_changed": rgba_changed,
            }

    return results


def check_lighting_randomization(model: MjModel, baseline: dict, tolerance: float = 1e-6) -> dict:
    """Check that lighting randomization is reproducible (same seed produces same values)."""
    results = {
        "randomized": {},
        "errors": [],
    }

    for light_id_str, baseline_light in baseline.items():
        light_id = int(light_id_str)
        light = model.light(light_id)

        # Check all lighting properties
        pos_diff = np.linalg.norm(np.array(light.pos) - np.array(baseline_light["pos"]))
        dir_diff = np.linalg.norm(np.array(light.dir) - np.array(baseline_light["dir"]))
        specular_diff = np.linalg.norm(
            np.array(light.specular) - np.array(baseline_light["specular"])
        )
        ambient_diff = np.linalg.norm(np.array(light.ambient) - np.array(baseline_light["ambient"]))
        diffuse_diff = np.linalg.norm(np.array(light.diffuse) - np.array(baseline_light["diffuse"]))
        light_active = light.active.item()
        active_diff = abs(int(light_active) - baseline_light["active"])

        # Check if randomized values match baseline (reproducibility)
        matches = (
            pos_diff <= tolerance
            and dir_diff <= tolerance
            and specular_diff <= tolerance
            and ambient_diff <= tolerance
            and diffuse_diff <= tolerance
            and active_diff == 0
        )

        results["randomized"][light_id] = {
            "name": baseline_light.get("name", f"light_{light_id}"),
            "pos_diff": float(pos_diff),
            "dir_diff": float(dir_diff),
            "specular_diff": float(specular_diff),
            "ambient_diff": float(ambient_diff),
            "diffuse_diff": float(diffuse_diff),
            "active_diff": active_diff,
            "matches": matches,  # Changed from "changed" to "matches"
        }

        if not matches:
            results["errors"].append(
                f"ERROR: Light {light_id} ({baseline_light.get('name', 'unknown')}) randomized values don't match baseline "
                f"(pos_diff={pos_diff:.6f}, dir_diff={dir_diff:.6f}, specular_diff={specular_diff:.6f}, "
                f"ambient_diff={ambient_diff:.6f}, diffuse_diff={diffuse_diff:.6f}, active_diff={active_diff})"
            )

    return results


def check_camera_image_randomization(
    model: MjModel,
    data: MjData,
    baseline: dict,
    tolerance: float = 0.01,
    save_path: Path = None,
) -> dict:
    """Check that camera images changed (indicating texture randomization).

    Loads and compares both baseline and randomized PNG images.
    """
    from molmo_spaces.renderer.opengl_rendering import MjOpenGLRenderer

    results = {
        "images": {},
        "errors": [],
    }

    # Initialize renderer
    renderer = MjOpenGLRenderer(model=model)
    mujoco.mj_forward(model, data)

    # Check each camera in baseline
    for cam_name, baseline_img in baseline.items():
        try:
            # Initialize image result dict
            results["images"][cam_name] = {}

            camera_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_CAMERA, cam_name)
            if camera_id < 0:
                results["errors"].append(f"Camera '{cam_name}' not found in model")
                continue

            # Render current randomized image first (so we can save it even if baseline loading fails)
            renderer.update(data, camera=cam_name)
            current_image = renderer.render()

            # Save current image as PNG (save it regardless of baseline loading success)
            if save_path:
                current_image_path = save_path / f"{cam_name}_randomized.png"
                cv2.imwrite(str(current_image_path), cv2.cvtColor(current_image, cv2.COLOR_RGB2BGR))
                results["images"][cam_name]["current_image_path"] = str(current_image_path)
                print(f"    Saved randomized image to: {current_image_path}")

            # Load baseline PNG image for comparison
            baseline_image_path = baseline_img.get("image_path")
            if not baseline_image_path:
                results["errors"].append(f"Baseline image path not found for camera '{cam_name}'")
                continue

            # Resolve baseline image path (it might be relative)
            baseline_image_path_resolved = Path(baseline_image_path)
            if not baseline_image_path_resolved.is_absolute():
                # Try resolving relative to RANDOMIZED_TEST_DATA_DIR
                baseline_image_path_resolved = RANDOMIZED_TEST_DATA_DIR / baseline_image_path
            elif not baseline_image_path_resolved.exists():
                # Try relative to RANDOMIZED_TEST_DATA_DIR as fallback
                baseline_image_path_resolved = (
                    RANDOMIZED_TEST_DATA_DIR / Path(baseline_image_path).name
                )

            if not baseline_image_path_resolved.exists():
                results["errors"].append(
                    f"Baseline image not found for camera '{cam_name}': {baseline_image_path} (tried: {baseline_image_path_resolved})"
                )
                continue

            baseline_image_bgr = cv2.imread(str(baseline_image_path_resolved))
            if baseline_image_bgr is None:
                results["errors"].append(
                    f"Failed to load baseline image for camera '{cam_name}': {baseline_image_path_resolved}"
                )
                continue

            # Convert BGR to RGB for comparison
            baseline_image = cv2.cvtColor(baseline_image_bgr, cv2.COLOR_BGR2RGB)
            results["images"][cam_name]["baseline_image_path"] = str(baseline_image_path_resolved)

            # Ensure images have the same shape for comparison
            if baseline_image.shape != current_image.shape:
                results["errors"].append(
                    f"Image shape mismatch for camera '{cam_name}': "
                    f"baseline {baseline_image.shape} vs current {current_image.shape}"
                )
                continue

            # Compare images directly
            # Calculate pixel-wise differences
            image_diff = np.abs(
                current_image.astype(np.float32) - baseline_image.astype(np.float32)
            )
            mean_pixel_diff = np.mean(image_diff)
            max_pixel_diff = np.max(image_diff)

            # Compare image statistics
            current_mean = np.mean(current_image)
            current_std = np.std(current_image)
            baseline_mean = np.mean(baseline_image)
            baseline_std = np.std(baseline_image)

            mean_diff = abs(current_mean - baseline_mean)
            std_diff = abs(current_std - baseline_std)

            # Hash comparison
            current_hash = hash(current_image.tobytes())
            baseline_hash = hash(baseline_image.tobytes())
            hash_match = current_hash == baseline_hash

            # Determine if image changed significantly
            changed = (
                mean_pixel_diff > tolerance
                or mean_diff > tolerance
                or std_diff > tolerance
                or not hash_match
            )

            results["images"][cam_name].update(
                {
                    "mean_pixel_diff": float(mean_pixel_diff),
                    "max_pixel_diff": float(max_pixel_diff),
                    "mean_diff": float(mean_diff),
                    "std_diff": float(std_diff),
                    "hash_match": hash_match,
                    "changed": changed,
                }
            )

            if not changed:
                results["errors"].append(
                    f"WARNING: Camera image from '{cam_name}' did not change significantly "
                    f"(mean_pixel_diff={mean_pixel_diff:.6f}, mean_diff={mean_diff:.6f}, "
                    f"std_diff={std_diff:.6f})"
                )
        except Exception as e:
            results["errors"].append(f"Error checking camera '{cam_name}': {e}")

    renderer.close()
    return results


def compare_image_visual_similarity(
    baseline_image_path: Path,
    randomized_image_path: Path,
    min_ssim: float = 0.0,
    max_ssim: float = 1.0,
) -> dict:
    """Compare visual similarity between baseline and randomized images using SSIM.

    Args:
        baseline_image_path: Path to baseline image (before randomization)
        randomized_image_path: Path to randomized image (after randomization)
        min_ssim: Minimum SSIM threshold (for testing that images differ)
        max_ssim: Maximum SSIM threshold (for testing that images match)

    Returns:
        dict with SSIM score and comparison results
    """
    results = {
        "ssim_score": None,
        "similar": None,
        "errors": [],
    }

    try:
        # Load images
        if not baseline_image_path.exists():
            results["errors"].append(f"Baseline image not found: {baseline_image_path}")
            return results

        if not randomized_image_path.exists():
            results["errors"].append(f"Randomized image not found: {randomized_image_path}")
            return results

        baseline_image_bgr = cv2.imread(str(baseline_image_path))
        randomized_image_bgr = cv2.imread(str(randomized_image_path))

        if baseline_image_bgr is None:
            results["errors"].append(f"Failed to load baseline image: {baseline_image_path}")
            return results

        if randomized_image_bgr is None:
            results["errors"].append(f"Failed to load randomized image: {randomized_image_path}")
            return results

        # Convert BGR to RGB
        baseline_image = cv2.cvtColor(baseline_image_bgr, cv2.COLOR_BGR2RGB)
        randomized_image = cv2.cvtColor(randomized_image_bgr, cv2.COLOR_BGR2RGB)

        # Ensure same shape
        if baseline_image.shape != randomized_image.shape:
            results["errors"].append(
                f"Image shape mismatch: baseline {baseline_image.shape} vs "
                f"randomized {randomized_image.shape}"
            )
            return results

        # Calculate SSIM (Structural Similarity Index)
        # SSIM ranges from -1 to 1, where 1 is perfect similarity
        # For RGB images, use channel_axis=2
        ssim_score = ssim(
            baseline_image,
            randomized_image,
            channel_axis=2,
            data_range=255,  # For uint8 images
        )

        results["ssim_score"] = float(ssim_score)

        # Check if similarity is within expected range
        # For reproducibility test: images should match (high SSIM, close to 1.0)
        # For randomization test: images should differ (low SSIM, close to 0.0)
        results["similar"] = min_ssim <= ssim_score <= max_ssim

        # Calculate additional metrics for debugging
        image_diff = np.abs(baseline_image.astype(np.float32) - randomized_image.astype(np.float32))
        results["mean_pixel_diff"] = float(np.mean(image_diff))
        results["max_pixel_diff"] = float(np.max(image_diff))
        results["percent_different_pixels"] = float(
            100.0 * np.sum(image_diff > 0) / image_diff.size
        )

    except Exception as e:
        results["errors"].append(f"Error comparing images: {e}")

    return results


def get_scene_path(house_type: str, house_index: int) -> str:
    """Get scene path from house type and index.

    Prefers "physics" variant if available, otherwise "base", otherwise first available.
    """
    scenes = get_scenes(house_type)
    scene_path_or_dict = scenes["train"][house_index]

    if isinstance(scene_path_or_dict, dict):
        # Prefer "physics" variant for randomization tests, then "base", then first available
        scene_path = (
            scene_path_or_dict.get("physics")
            or scene_path_or_dict.get("base")
            or list(scene_path_or_dict.values())[0]
        )
    else:
        scene_path = scene_path_or_dict

    if scene_path is None:
        raise ValueError(f"Scene not found for {house_type} house_index {house_index}")

    return str(scene_path)


def _setup_model_and_randomizers(
    scene_path: str,
    config: RandomizationTestConfig,
) -> tuple[MjModel, MjData, dict]:
    """Setup model and randomizers for testing."""
    print(f"Loading scene from: {scene_path}")

    if not os.path.exists(scene_path):
        raise FileNotFoundError(f"Scene path does not exist: {scene_path}")

    # Create output directory for saving images
    OUTPUT_DATA_DIR.mkdir(parents=True, exist_ok=True)

    # Load model
    spec = mujoco.MjSpec.from_file(scene_path)
    setup_empty_materials(spec)

    # Compile model first to calculate camera position
    model_temp = spec.compile()
    data_temp = MjData(model_temp)
    mujoco.mj_forward(model_temp, data_temp)

    # Add camera at a fixed position above floor center
    # Uses the same function as generate_test_data_randomization.py to ensure identical camera setup
    add_test_camera(spec, model_temp, data_temp)

    # Recompile with camera added
    model = spec.compile()
    data = MjData(model)
    mujoco.mj_forward(model, data)

    print(f"Loaded model: {model.ngeom} geoms, {model.nlight} lights, {model.ntex} textures")

    # Create random state from seed
    if config.seed is not None:
        random_state = np.random.RandomState(config.seed)
    else:
        random_state = None

    # Initialize randomizers
    randomizers = {}

    if config.enable_lighting_randomization:
        randomizers["lighting"] = LightingRandomizer(
            model=model,
            random_state=random_state,
            randomize_position=True,
            randomize_direction=True,
            randomize_specular=True,
            randomize_ambient=True,
            randomize_diffuse=True,
            randomize_active=True,
        )
        print("  ✓ Lighting randomizer initialized")

    if config.enable_texture_randomization:
        scene_metadata = get_scene_metadata(scene_path)
        randomizers["texture"] = TextureRandomizer(
            model=model,
            random_state=random_state,
            randomize_geom_rgba=True,
            randomize_material_rgba=True,
            randomize_material_specular=True,
            randomize_material_shininess=True,
            randomize_texture=True,
            scene_metadata=scene_metadata,
        )
        print("  ✓ Texture randomizer initialized")

    if config.enable_dynamics_randomization:
        randomizers["dynamics"] = DynamicsRandomizer(
            random_state=random_state,
            randomize_friction=True,
            randomize_mass=True,
            randomize_inertia=True,
        )
        print("  ✓ Dynamics randomizer initialized")

    return model, data, randomizers


@pytest.fixture(scope="session")
def config():
    """Fixture providing RandomizationTestConfig."""
    return RandomizationTestConfig()


@pytest.fixture(scope="session")
def install_scenes(config: RandomizationTestConfig):
    """Install scenes from molmospaces-resources before running tests."""
    scene = get_scenes(config.house_type)["train"][config.house_index]
    if isinstance(scene, dict):
        # Use "physics" variant if available, otherwise use "base" or first available
        scene_path = scene.get("physics") or scene.get("base") or list(scene.values())[0]
    else:
        scene_path = scene

    install_scene_with_objects_and_grasps_from_path(scene_path)


@pytest.fixture(scope="session")
def scene_path(config: RandomizationTestConfig, install_scenes):
    """Fixture providing scene path from config.

    Note: install_scenes fixture ensures the scene is installed from molmospaces-resources.
    """
    return get_scene_path(config.house_type, config.house_index)


@pytest.fixture(scope="session")
def baseline_file(scene_path: str):
    """Fixture providing baseline metadata file path."""
    scene_stem = Path(scene_path).stem
    baseline_file = RANDOMIZED_TEST_DATA_DIR / f"baseline_{scene_stem}_metadata.json"

    if not baseline_file.exists():
        pytest.skip(
            f"Baseline file not found: {baseline_file}\n"
            f"Please run generate_test_data_randomization.py first to generate baseline data."
        )

    return baseline_file


def test_dynamics_randomization(
    config: RandomizationTestConfig, scene_path: str, baseline_file: Path
):
    """Test that dynamics randomization works correctly."""
    if not config.enable_dynamics_randomization:
        pytest.skip("Dynamics randomization is disabled in config")

    # Load baseline data
    print(f"Loading baseline data from: {baseline_file}")
    baseline_data = load_baseline_data(baseline_file)

    # Setup model and randomizers
    model, data, randomizers = _setup_model_and_randomizers(scene_path, config)
    dynamics_randomizer = randomizers.get("dynamics")

    if dynamics_randomizer is None:
        pytest.skip("Dynamics randomizer not initialized")

    # Apply dynamics randomization
    print("\nApplying dynamics randomization...")
    objects = get_all_bodies_with_joints_as_mlspaces_objects(model, data)
    if objects:
        dynamics_randomizer.randomize_objects(objects)
        print(f"  ✓ Dynamics randomized for {len(objects)} objects")
    else:
        pytest.skip("No objects found for dynamics randomization")

    mujoco.mj_forward(model, data)

    # Check results
    print("\nChecking dynamics randomization...")
    dynamics_results = check_dynamics_randomization(
        model, data, baseline_data["dynamics"], dynamics_randomizer
    )

    num_randomized = sum(
        1 for v in dynamics_results["randomized"].values() if v.get("status") == "OK - randomized"
    )
    print(f"  Randomized: {num_randomized}/{len(dynamics_results['randomized'])} objects")
    print(f"  Errors: {len(dynamics_results['errors'])}")

    # Assertions
    assert len(dynamics_results["errors"]) == 0, (
        f"Found {len(dynamics_results['errors'])} errors in dynamics randomization"
    )
    assert num_randomized > 0, "No objects were randomized for dynamics"


def test_texture_randomization(
    config: RandomizationTestConfig, scene_path: str, baseline_file: Path
):
    """Test that texture/material and camera image randomization works correctly."""
    if not config.enable_texture_randomization:
        pytest.skip("Texture randomization is disabled in config")

    # Load baseline data
    print(f"Loading baseline data from: {baseline_file}")
    baseline_data = load_baseline_data(baseline_file)

    # Setup model and randomizers
    model, data, randomizers = _setup_model_and_randomizers(scene_path, config)
    texture_randomizer = randomizers.get("texture")

    if texture_randomizer is None:
        pytest.skip("Texture randomizer not initialized")

    # Apply texture randomization
    print("\nApplying texture randomization...")
    texture_randomizer.randomize_by_category(data)
    print("  ✓ Textures randomized")

    mujoco.mj_forward(model, data)

    # Check texture/material results
    print("\nChecking texture/material randomization...")
    texture_results = check_texture_material_randomization(model, baseline_data["texture_material"])
    print(f"  Randomized: {len(texture_results['randomized'])} geoms")
    print(f"  Errors: {len(texture_results['errors'])}")

    # Check camera images
    print("\nChecking camera images...")
    camera_results = check_camera_image_randomization(
        model, data, baseline_data["camera_images"], save_path=OUTPUT_DATA_DIR
    )
    num_changed = sum(1 for v in camera_results["images"].values() if v.get("changed", False))
    print(f"  Changed: {num_changed}/{len(camera_results['images'])} images")
    print(f"  Errors/Warnings: {len(camera_results['errors'])}")
    print(f"  Saved randomized images to: {OUTPUT_DATA_DIR}")

    # Compare visual similarity of baseline and randomized images
    print("\nComparing visual similarity of baseline and randomized images...")
    for cam_name, cam_data in camera_results["images"].items():
        baseline_image_path = cam_data.get("baseline_image_path")
        randomized_image_path = cam_data.get("current_image_path")

        if baseline_image_path and randomized_image_path:
            similarity_results = compare_image_visual_similarity(
                Path(baseline_image_path),
                Path(randomized_image_path),
                min_ssim=0.0,  # Images should differ (randomization occurred)
                max_ssim=0.95,  # Allow some similarity but not too much
            )

            if similarity_results["errors"]:
                print(f"  {cam_name}: Errors - {similarity_results['errors']}")
            else:
                ssim_score = similarity_results["ssim_score"]
                print(
                    f"  {cam_name}: SSIM={ssim_score:.4f}, "
                    f"mean_diff={similarity_results['mean_pixel_diff']:.2f}, "
                    f"max_diff={similarity_results['max_pixel_diff']:.2f}, "
                    f"diff_pixels={similarity_results['percent_different_pixels']:.2f}%"
                )

                # Images should be different (low SSIM) if randomization worked
                # SSIM < 0.95 indicates meaningful visual difference
                if ssim_score >= 0.95:
                    camera_results["errors"].append(
                        f"WARNING: {cam_name} images are too similar (SSIM={ssim_score:.4f}), "
                        f"randomization may not have affected visual appearance"
                    )

    # Assertions
    assert len(texture_results["errors"]) == 0, (
        f"Found {len(texture_results['errors'])} errors in texture/material randomization"
    )
    assert len(texture_results["randomized"]) > 0, "No geoms were randomized for texture/material"
    assert len(camera_results["errors"]) == 0, (
        f"Found {len(camera_results['errors'])} errors in camera image randomization"
    )
    assert num_changed > 0, "Camera images did not change after texture randomization"


def test_lighting_randomization(
    config: RandomizationTestConfig, scene_path: str, baseline_file: Path
):
    """Test that lighting randomization works correctly."""
    if not config.enable_lighting_randomization:
        pytest.skip("Lighting randomization is disabled in config")

    # Load baseline data
    print(f"Loading baseline data from: {baseline_file}")
    baseline_data = load_baseline_data(baseline_file)

    # Setup model and randomizers
    model, data, randomizers = _setup_model_and_randomizers(scene_path, config)
    lighting_randomizer = randomizers.get("lighting")

    if lighting_randomizer is None:
        pytest.skip("Lighting randomizer not initialized")

    # Apply lighting randomization
    print("\nApplying lighting randomization...")
    lighting_randomizer.randomize(data)
    print("  ✓ Lighting randomized")

    mujoco.mj_forward(model, data)

    # Check results
    print("\nChecking lighting randomization reproducibility...")
    lighting_results = check_lighting_randomization(model, baseline_data["lighting"])
    num_matches = sum(1 for v in lighting_results["randomized"].values() if v.get("matches", False))
    num_total = len(lighting_results["randomized"])
    print(f"  Matches baseline: {num_matches}/{num_total} lights")
    print(f"  Errors: {len(lighting_results['errors'])}")

    # Assertions
    # All lights should match the baseline (same seed should produce same randomized values)
    assert len(lighting_results["errors"]) == 0, (
        f"Found {len(lighting_results['errors'])} errors in lighting randomization reproducibility:\n"
        + "\n".join(f"  - {err}" for err in lighting_results["errors"][:10])
        + (
            f"\n  ... and {len(lighting_results['errors']) - 10} more errors"
            if len(lighting_results["errors"]) > 10
            else ""
        )
    )
    assert num_matches == num_total, (
        f"Only {num_matches}/{num_total} lights matched the baseline (expected all to match with same seed)"
    )
